Created a get-user API and a supertest for the new endpoint
raghunat/hotspot pull request #47
Opened 2017-03-07 13:38 UTC by angkimbrell1

2017-03-09 10:45 UTC, stephenthedev requested changes

2017-03-09 10:45 UTC, raghunat commented on gateway-api/users-api/api/get-user.spec.js
> +        res.text.should.equal(
This is a syntax error. To run your tests, run `npm test` from within the users-api folder.

Also, validations should look like this:

```javascript
res.body.username.should.equal('bob');
```

2017-03-09 10:45 UTC, raghunat commented
@angkimbrell1 You are also missing the route in app.js

2017-03-09 15:52 UTC, angkimbrell1 commented on gateway-api/users-api/api/get-user.spec.js
> +        res.text.should.equal(
I've tried this and it gives me a TypeError stating that it cannot read property 'should' of undefined.

2017-03-10 11:43 UTC, stephenthedev requested changes

2017-03-10 11:43 UTC, raghunat commented on gateway-api/users-api/api/get-user.spec.js
> +describe('/get-user', () => {
change to /users/:id

2017-03-10 11:43 UTC, raghunat commented on gateway-api/users-api/app.js
> +app.get('/users/:id', require('./api/get-user.js')());
This file should not be here. Your route should be in the users-api folder, not a new file in the gateway-api

2017-03-18 11:16 UTC, raghunat commented
@angkimbrell1 up

2017-03-18 14:09 UTC, angkimbrell1 commented on gateway-api/users-api/app.js
> +app.get('/users/:id', require('./api/get-user.js')());
So the users-api folder should not be within the gateway-api folder?

2017-04-01 18:30 UTC, merged