Issue 69 create spots with db
raghunat/hotspot pull request #80
Opened 2017-03-27 23:12 UTC by siragusamatt

Ability to create spots and send data to database #69

2017-04-01 18:17 UTC, stephenthedev requested changes

2017-04-01 18:17 UTC, raghunat commented on spots-api/api/post-spots.js
> +    res.json(req.body);
This line shouldn't be here, it will respond right away incorrectly.

2017-04-03 17:12 UTC, siragusamatt commented
Changed what was requested. Deleted the line in spots-api/api/post-spots.js

2017-04-04 01:31 UTC, stephenthedev requested changes

2017-04-04 01:31 UTC, raghunat commented on spots-api/api/post-spots.js
> +      if(err) throw err;
This should be an error response like demonstrated in alive.js

2017-04-04 22:15 UTC, merged